[package]
edition      = "2024"
name         = "my-first-esp-rust"
rust-version = "1.88"
version      = "0.1.0"

[[bin]]
name = "my-first-esp-rust"
path = "./src/bin/main.rs"

[dependencies]
esp-hal = { version = "~1.1.0", features = ["esp32", "unstable"] }


esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32"] }

critical-section = "1.2.0"
esp-alloc        = "0.10.0"

display-interface-spi = "0.5.0"
ili9341 = "0.6.0"
embedded-hal-bus = "0.3.0"
embedded-graphics-core = "0.4.1"

egui-euc = { git = "https://github.com/Masterchef365/egui-euc.git", branch = "no_std", default-features = false }
egui = { version = "0.32.0", default-features = false }

euc = { git = "https://github.com/zesterer/euc.git", rev = "e8f7aee", default-features = false, features = ["micromath"] }
vek = { version = "0.17", default-features = false, features = ["rgba", "libm"] }

#fearless_simd = { version = "0.3.0", default-features = false }

[patch.crates-io]
#egui = { git = "https://github.com/Masterchef365/egui.git", branch = "no_std" }
egui = { path = "../egui/crates/egui/" }


# For fine tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
# Always build with some optimizations enabled.
opt-level = "s"

[profile.release]
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug         = 2     # prefer slower builds but better debugging experience
lto           = 'fat'
opt-level     = 's'
